"""Structured extraction and storage error codes."""

from enum import StrEnum


class ExtractionErrorCode(StrEnum):
    """Error codes defined by SRS section 31."""

    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_CORRUPTED = "FILE_CORRUPTED"
    PDF_PARSE_FAILED = "PDF_PARSE_FAILED"
    DOCX_PARSE_FAILED = "DOCX_PARSE_FAILED"
    OCR_FAILED = "OCR_FAILED"
    OCR_LOW_CONFIDENCE = "OCR_LOW_CONFIDENCE"
    NO_TEXT_DETECTED = "NO_TEXT_DETECTED"
    PARTIAL_EXTRACTION = "PARTIAL_EXTRACTION"
    PROCESSING_TIMEOUT = "PROCESSING_TIMEOUT"
    STORAGE_ERROR = "STORAGE_ERROR"
    UNKNOWN_EXTRACTION_ERROR = "UNKNOWN_EXTRACTION_ERROR"
